name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-ci.txt

      - name: Install
        run: |
          python -m pip install --upgrade pip
          if exist requirements-ci.txt (pip install -r requirements-ci.txt) else (pip install -r requirements.txt)
          pip install pytest

      - name: Debug env
        run: |
          python -c "import sys,platform;print(sys.version);print(platform.platform())"

      - name: Smoke tests (tolerate no tests)
        shell: pwsh
        run: |
          pytest -q
          if ($LASTEXITCODE -eq 5) { Write-Host "No tests collected; treating as pass"; exit 0 }
          exit $LASTEXITCODE
