name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-ci.txt

      - name: Install (minimal for smoke)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-ci.txt ]; then pip install --only-binary ":all:" -r requirements-ci.txt; else pip install -r requirements.txt; fi

      - name: Debug pip/env
        run: |
          python -m pip debug --verbose
          python - << 'PY'
          import sys, platform
          print(sys.version)
          print(platform.platform())
          PY

      - name: Sanity import (tolerant)
        run: |
          python - << 'PY'
          try:
              from project.env.retirement_env import RetirementEnv
              env = RetirementEnv(horizon_years=1, market_mode="iid", mu_risky=0.0, sigma_risky=0.0, r_safe=0.0)
              print("Sanity OK")
          except Exception as e:
              print("Sanity import skipped:", e)
          PY

      - name: Smoke tests (skip cli_help to avoid heavy imports)
        run: |
          pytest -q || EC=True
          # pytest exit code 5 = no tests collected -> pass
          if [ "" = "5" ]; then echo "No tests collected; treating as pass"; exit 0; fi
          exit 
